<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo($owl_lang->lang_code) ?>" >
<head>
<title><?php print $default->site_title . " " . $default->version ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=<?php echo($default->charset) ?>"></meta>
<link rel="shortcut icon" href="<?php print $default->owl_graphics_url?>/favicon.ico"></link>
<link rel="bookmark" href="<?php print $default->owl_graphics_url?>/favicon.ico"></link>
<link rel="stylesheet" type="text/css" title="style1" href="<?php print $default->owl_root_url?>/install/lib/install.css"></link>
</head>
<body>
<table border="0" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td class="logo" width="100%"><img src="images/owl_logo1.gif" border="0" alt="Owl Intranet Logo"></img></td>
</tr>
</table>
<table cellpadding="0" cellspacing="0">
<tr>
  <td>
