<?php
/**
 * dwnl_file_to_browser.php -- API Sample Program to download directly to browser
 * 
 * Author: Steve Bourgeois <owl@bozzit.com>
 * 
 * Copyright (c) 2006-2014 Bozz IT Consulting Inc
 *
 * Licensed under the GNU GPL. For full terms see the file LICENSE.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 * 
 */

include('./lib/client.lib.php');

$sUrl = 'http://www.example.com/doxbox/API/serverapi.php';

$sAPIKey = urlencode('<API KEY GENERATED BY genapikey.php>');

/**************************
* Print The API Version 
***************************/
$fields = array('CallFunction' => urlencode('Version')); // Method to call

$sApiResult = fDmsApiClient($fields);


/**************************
* Authenticate to Owl
***************************/
$fields = array('CallFunction' => urlencode('VerifyCredential'), // Method to call
                'Args[0]' => urlencode('admin'),  // Username
                'Args[1]' => urlencode('admin'),  // Passwords
                'Args[2]' => $sAPIKey             // API Key 

	);

$sApiResult = fDmsApiClient($fields);

/**
* The Default return mode is JSON, since the APIKey is checked in the construct of the class
* the result in the case of API Key failiure will be a JSON obect. So For this Call we need
* To make sure its not JSON Object before trying to parse the XML.
*/

if (isJson($sApiResult))
{
   /**
   * Print the Error Code Or add Error Handling here
   */
   print("<xmp>" . $sApiResult . "</xmp>");
   exit;
}
else // We probably got a login error OR a session ID but assume all is OK
{
   libxml_use_internal_errors(true);
   $oApiResult = new SimpleXMLElement('<dms_response />');
   $oApiResult = simplexml_load_string($sApiResult);
   if (!$oApiResult)
   {
      print("<xmp>" . $sApiResult . "</xmp>");
      exit;
   }
}

/**************************
* Download  a Single file
***************************/

$fields = array('CallFunction' => urlencode('DownloadFile'), // Method to call
                'Args[0]' => urlencode((string) $oApiResult->sessid), // Valid Owl Session
                //'Args[1]' => urlencode($oCreateFileResult->new_file_id) // File ID of the Sample File Created above
                'Args[1]' => urlencode('311') // File ID of the Sample File Created above
	);

$aApiResult = fDmsApiClient($fields, 1);

if (isJson($aApiResult['body']))
{
   /**
   * Print the Error Code Or add Error Handling here
   */
   print("<xmp>" . $sApiResult . "</xmp>");
}
else 
{
   libxml_use_internal_errors(true);
   $oApiResult = new SimpleXMLElement('<dms_response />');
   $oApiResult = simplexml_load_string($aApiResult['body']);
   if (!$oApiResult)
   {
      $aHeaderContent = http_parse_headers($aApiResult['header']);
      header("Content-Disposition: " . $aHeaderContent['Content-Disposition']);
      header("Content-Location: " . $aHeaderContent['Content-Location']);
      header("Content-Type: " . $aHeaderContent['Content-Type']);
      header("Content-Length: " . $aHeaderContent['Content-Length']);
      header("Expires: 0");
      print($aApiResult['body']);
   }
}



/**************************
* Logout / destroy the  Owl Session
***************************/
$fields = array('CallFunction' => urlencode('Logout'), // Method to call
		'Args[0]' => urlencode((string) $oApiResult->sessid) // Valid Owl Session 
	);

$sApiResult = fDmsApiClient($fields);

